import { IButton } from "./IButton";
import { ISlide } from "./ISlide";

export interface IState {
  hasAudio: boolean;
  hasSlideshow: boolean;
  hasVideo: boolean;
  hasVinyl: boolean;
  isSlideshowReady?: boolean;
  imageDisplayed?: null;
  duration: number;
  slideshow?: ISlide[];
  isAudioReady?: boolean;
  isVinylReady?: boolean;
  audio?: string;
  rpm?: number;
  vinyl?: string;
  height: number;
  width: number;
  volume: number;
  pastVolume: number;
  allowFullFrame: boolean;
  currentTime: number;
  logo?: { img: string, href?: string };
  buttons: IButton[];
  color: string;
  thumbnail?: string;
  muted: boolean;
  autoplay: boolean;
  style: Record<string, string>;
  id?: string;
  isTestEnvironment: boolean;
  initTime: Date;
  title?: string;
  link?: string;
  isLoading: boolean;
  isPlayerHighlighted: boolean;
  isInitialized: boolean;
  isLargePlayButtonHighlighted: boolean;
  isPlaying: boolean;
  isReadingTerminated: boolean;
  showVolumeSlider: boolean;
  isFullscreen: boolean;
  isFullscreenActivated: boolean;
  highlightProgressBar: boolean;
  allowUnhighlightProgressBar: boolean;
  volumeSliderLeftMargin: string;
  allowMouseLeaveVolumeSlider: boolean;
  showMenus: boolean;
  allowMenuHiding: boolean;
  showCursor: boolean;
  timeLastUserAction: Date;
  askTime: number;
  askNextImage: null;
  askPreviousImage: null;
  videoHeight: null;
  videoWidth: null;
  timeRangeBuffered: number;
  channelsWait: boolean;
}
